export const RTC_TOPIC = {
  // Publishers (send to robot)
  SPORT_MOD: 'rt/api/sport/request',
  OBSTACLES_AVOID: 'rt/api/obstacles_avoid/request',
  VUI: 'rt/api/vui/request',
  BASHRUNNER: 'rt/api/bashrunner/request',
  MOTION_SWITCHER: 'rt/api/motion_switcher/request',
  ROBOT_STATE: 'rt/api/robot_state/request',
  GAS_SENSOR: 'rt/api/gas_sensor/request',
  PET: 'rt/api/pet/request',
  CONFIG: 'rt/api/config/request',
  VIDEOHUB: 'rt/api/videohub/request',
  AUDIOHUB: 'rt/api/audiohub/request',
  FOURG_AGENT: 'rt/api/fourg_agent/request',
  WIRELESS_CONTROLLER: 'rt/wirelesscontroller',
  LIDAR_SWITCH: 'rt/utlidar/switch',
  LOW_CMD: 'rt/lowcmd',

  // Subscribers (receive from robot)
  LOW_STATE: 'rt/lf/lowstate',
  LF_SPORT_MOD_STATE: 'rt/lf/sportmodestate',
  LIDAR_ARRAY: 'rt/utlidar/voxel_map_compressed',
  LIDAR_STATE: 'rt/utlidar/lidar_state',
  ROBOT_ODOM: 'rt/utlidar/robot_pose',
  MULTIPLE_STATE: 'rt/multiplestate',
  SELFTEST: 'rt/selftest',
  SERVICE_STATE: 'rt/servicestate',
  BATTERY_ALARM: 'rt/lf/battery_alarm',
  UWB_STATE: 'rt/uwbstate',
  PUBLIC_NETWORK_STATUS: 'rt/public_network_status',

  // USLAM (3D LiDAR Mapping / Navigation / Patrol)
  USLAM_CMD: 'rt/uslam/client_command',
  USLAM_SERVER_LOG: 'rt/uslam/server_log',
  USLAM_CLOUD_WORLD: 'rt/uslam/frontend/cloud_world_ds',
  USLAM_ODOM: 'rt/uslam/frontend/odom',
  USLAM_CLOUD_MAP: 'rt/uslam/cloud_map',
  USLAM_LOC_ODOM: 'rt/uslam/localization/odom',
  USLAM_LOC_CLOUD: 'rt/uslam/localization/cloud_world',
  USLAM_NAV_PATH: 'rt/uslam/navigation/global_path',
  USLAM_GRID_MAP: 'rt/mapping/grid_map',
} as const;

export const SPORT_CMD = {
  // Shared across Normal/AI/MCF (1xxx)
  Damp: 1001,
  BalanceStand: 1002,
  StopMove: 1003,
  StandUp: 1004,
  StandDown: 1005,
  RecoveryStand: 1006,
  Euler: 1007,
  Move: 1008,
  Sit: 1009,
  RiseSit: 1010,
  SwitchGait: 1011,
  Trigger: 1012,
  BodyHeight: 1013,
  FootRaiseHeight: 1014,
  SpeedLevel: 1015,
  Hello: 1016,
  Stretch: 1017,
  TrajectoryFollow: 1018,
  ContinuousGait: 1019,
  Content: 1020,
  Wallow: 1021,
  Dance1: 1022,
  Dance2: 1023,
  GetBodyHeight: 1024,
  GetFootRaiseHeight: 1025,
  GetSpeedLevel: 1026,
  SwitchJoystick: 1027,
  Pose: 1028,
  Scrape: 1029,
  FrontFlip: 1030,
  FrontJump: 1031,
  FrontPounce: 1032,
  WiggleHips: 1033,
  GetState: 1034,
  EconomicGait: 1035,
  FingerHeart: 1036,
  // MCF-specific IDs (2xxx) — used by newer firmware
  LeftFlip: 2041,
  BackFlip: 2043,
  HandStand: 2044,
  FreeWalk: 2045,
  FreeBound: 2046,
  FreeJump: 2047,
  FreeAvoid: 2048,
  CrossStep: 2051,
  LeadFollow: 2056,
  // MCF IDs that differ from Normal
  StaticWalk: 1061,
  TrotRun: 1062,
  MCF_EconomicGait: 1063,
  // AI-only (1xxx, also work in MCF for some)
  WalkStair: 1049,
} as const;

export const DATA_CHANNEL_TYPE = {
  VALIDATION: 'validation',
  SUBSCRIBE: 'subscribe',
  UNSUBSCRIBE: 'unsubscribe',
  MSG: 'msg',
  REQUEST: 'req',
  RESPONSE: 'res',
  VID: 'vid',
  AUD: 'aud',
  ERR: 'err',
  ERRORS: 'errors',
  HEARTBEAT: 'heartbeat',
  RTC_INNER_REQ: 'rtc_inner_req',
  RTC_REPORT: 'rtc_report',
} as const;
